stages:
  - deploy

variables:
  - TEST_ROOT: "C:\inetpub\wwwroot\ViperTest\"
  - TEST_BUILD: "C:\inetpub\wwwroot\ViperTest\build"
  - DEV_ROOT: "C:\inetpub\wwwroot\ViperDev\"
  - DEV_BUILD: "C:\inetpub\wwwroot\ViperDev\build"

deploy test:
  script:
    - dnvm use 1.0.0-beta7 -p
    - appcmd stop sites "ViperTest"
    - Remove-Item2 -Force -Recurse -Path $TEST_ROOT
    - New-Item $TEST_ROOT -type directory
    - dnu restore src\viper\
    - dnu publish src\viper\ -o "TEST_BUILD" --runtime active
    - appcmd start sites "ViperTest"
  stage: deploy
  only: 
    - test
  tags:
    - vipertest

deploy dev:
  script:
    - dnvm use 1.0.0-beta7 -p
    - appcmd stop sites "ViperDev"
    - Remove-Item2 -Force -Recurse -Path $DEV_ROOT
    - New-Item $DEV_ROOT -type directory
    - dnu restore src\viper\
    - dnu publish src\viper\ -o "DEV_BUILD" --runtime active
    - appcmd start sites "ViperDev"
  stage: deploy
  except:
    - test
    - master
  tags:
    - viper
    - dev