stages:
  - deploy

deploy test:
  script:
    - dnvm use 1.0.0-beta7 -p
    - appcmd stop sites "ViperTest"
    - Remove-Item2 -Force -Recurse -Path C:\inetpub\wwwroot\ViperTest\
    - New-Item C:\inetpub\wwwroot\ViperTest\ -type directory
    - dnu restore src\viper\
    - dnu publish src\viper\ -o "C:\inetpub\wwwroot\ViperTest\" --runtime active
    - appcmd start sites "ViperTest"
  stage: deploy
  only: 
    - test
  tags:
    - vipertest

deploy dev:
  script:
    - dnvm use 1.0.0-beta7 -p
    - appcmd stop sites "ViperDev"
    - SET src=./
    - SET stage=/c/inetpub/wwwroot/ViperDev/stage/
    - SET site=/c/inetpub/wwwroot/ViperDev/site/
    - \%bash\% "scripts/rm-except-node-modules.sh \%src\% \%stage\%" 
    - \%bash\% "echo cp \%src\%* \%stage\% -R"
    - \%bash\% "echo rm -rf -- \%site\%"
    - \%bash\% "echo cp \%stage\%* \%site\% -R"
    - appcmd start sites "ViperDev
  stage: deploy
  except:
    - test
    - master
  tags:
    - viper
    - dev