stages:
  - deploy

deploy test:
  script:
    - appcmd stop sites "ViperTest"
    - Start-Sleep -s 5
    - dnu restore src\viper\
    - dnu publish src\viper\ -o "C:\inetpub\wwwroot\ViperTest\build\" --runtime active
    - appcmd start sites "ViperTest"
  stage: deploy
  only: 
    - test
  tags:
    - vipertest