stages:
  - deploy

deploy test:
  script:
    - dnvm use 1.0.0-beta7 -p
    - appcmd stop sites "ViperTest"
    - Remove-Item2 -Force -Recurse -Path C:\inetpub\wwwroot\ViperTest\
    - New-Item C:\inetpub\wwwroot\ViperTest\ -type directory
    - dnu restore src\viper\
    - dnu publish src\viper\ -o "C:\inetpub\wwwroot\ViperTest\" --runtime active
    - appcmd start sites "ViperTest"
  stage: deploy
  only: 
    - test
  tags:
    - vipertest

deploy dev:
  script:
    - dnvm use 1.0.0-beta7 -p
    - appcmd stop sites "ViperDev"
    - Remove-Item2 -Force -Recurse -Path C:\inetpub\wwwroot\ViperDev\
    - New-Item C:\inetpub\wwwroot\ViperDev\ -type directory
    - dnu restore src\viper\
    - dnu publish src\viper\ -o "C:\inetpub\wwwroot\ViperDev\" --runtime active
    - appcmd start sites "ViperDev"
  stage: deploy
  except:
    - test
    - master
  tags:
    - viper
    - dev