stages:
  - deploy

execute deploy script:
  script:
    - appcmd stop sites "ViperTest"
    - appcmd recycle apppool "ViperTest"
    - dnu restore src\viper\
    - dnu publish src\viper\ -o "C:\inetpub\wwwroot\ViperTest\build\" --runtime active
    - appcmd start sites "ViperTest"
  stage: deploy
  only: 
    - master
  tags:
    - vipertest